name: ci/github-actions
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  argschema:
    name: ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "windows-latest", "ubuntu-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env
      - name: Install
        run: |
          conda activate test-env
          pip install codecov
          pip install .[TESTING]
      - name: WindowsInstall
        if: ${{ matrix.os == 'windows-latest' }}
        run: pip install .[WINDOWS]
      - name: Test
        run: |
          python -m pytest --cov argschema --cov-report xml
          bash <(curl -s https://codecov.io/bash)
